%YAML:1.0
---
SGBM:
# must define for opencv check
    name: StereoMatcher.SGBM

# Margin in percentage by which the best (minimum) computed cost function value should "win" the second best value to consider the found match correct.
# Normally, a value within the 5-15 range is good enough.
    uniquenessRatio: 10

# Maximum size of smooth disparity regions to consider their noise speckles and invalidate.
# Set it to 0 to disable speckle filtering.
# Otherwise, set it somewhere in the 50-200 range.
    speckleWindowSize: 100

# Maximum disparity variation within each connected component.
# If you do speckle filtering, set the parameter to a positive value, it will be implicitly multiplied by 16.
# Normally, 1 or 2 is good enough.
    speckleRange: 32

# Minimum possible disparity value.
# Normally, it is zero but sometimes rectification algorithms
# can shift images, so this parameter needs to be adjusted accordingly.
    minDisparity: 0

# Maximum allowed difference (in integer pixel units) in the left-right disparity check.
# Set it to a non-positive value to disable the check.
    disp12MaxDiff: 1

# Truncation value for the prefiltered image pixels.
# The algorithm first computes x-derivative at each pixel and clips its value by [-preFilterCap, preFilterCap] interval.
# The result values are passed to the Birchfield-Tomasi pixel cost function.
    preFilterCap: 63

# Maximum disparity minus minimum disparity.
# The value is always greater than zero.
# In the current implementation, this parameter must be divisible by 16.
    numDisparities: 64

# Matched block size. It must be an odd number >=1 .
# Normally, it should be somewhere in the 3..11 range.
    blockSize: 3

# The first parameter controlling the disparity smoothness. See below.
    P1: 72

# The second parameter controlling the disparity smoothness.
# The larger the values are, the smoother the disparity is.
# P1 is the penalty on the disparity change by plus or minus 1 between neighbor pixels.
# P2 is the penalty on the disparity change by more than 1 between neighbor pixels.
# The algorithm requires P2 > P1 .
    P2: 188

BM:
# must define for opencv check
    name: StereoMatcher.BM
    uniquenessRatio: 60
    speckleWindowSize: 100
    speckleRange: 4
    minDisparity: 0
    disp12MaxDiff: 1
    preFilterCap: 31
# the disparity search range.
# For each pixel algorithm will find the best disparity from 0 (default minimum disparity) to numDisparities.
# The search range can then be shifted by changing the minimum disparity.
    numDisparities: 64

# the linear size of the blocks compared by the algorithm.
# The size should be odd (as the block is centered at the current pixel).
# Larger block size implies smoother, though less accurate disparity map.
# Smaller block size gives more detailed disparity map,
# but there is higher chance for algorithm to find a wrong correspondence.
    blockSize: 15
    preFilterSize: 9
    textureThreshold: 10
